name: Deploy to Hostinger

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Install sshpass (to use password)
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy with rsync using password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avzr --delete -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u669089836/domains/monteromaintenance.com/public_html/
