name: Deploy via SFTP

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Install LFTP (SFTP client)
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP
        run: |
          lftp -c "set sftp:auto-confirm yes; open -u ${{ secrets.SSH_USER }},${{ secrets.SSH_PASSWORD }} sftp://${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}; mirror -R ./dist /home/u669089836/domains/monteromaintenance.com/public_html/ --delete --verbose"
